import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-neutral-50 text-neutral-900`}
      >
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar Navigation */}
          <aside className="w-64 bg-indigo-900 text-white min-h-screen flex flex-col pt-8">
            <h1 className="text-xl font-bold px-6 mb-8 tracking-wider">シフト自動作成システム</h1>
            <nav className="flex-1 flex flex-col gap-2 px-4">
              <Link href="/" className="px-4 py-3 rounded-md hover:bg-indigo-800 transition-colors flex items-center gap-3">
                <span className="text-lg">カレンダー</span>
              </Link>
              <Link href="/staff" className="px-4 py-3 rounded-md hover:bg-indigo-800 transition-colors flex items-center gap-3">
                <span className="text-lg">スタッフ管理</span>
              </Link>
              <Link href="/requests" className="px-4 py-3 rounded-md hover:bg-indigo-800 transition-colors flex items-center gap-3">
                <span className="text-lg">希望休入力</span>
              </Link>
              <Link href="/settings" className="px-4 py-3 rounded-md hover:bg-indigo-800 transition-colors flex items-center gap-3 mt-auto mb-8">
                <span className="text-lg">基本設定</span>
              </Link>
            </nav>
          </aside>
          
          {/* Main Content Area */}
          <main className="flex-1 overflow-y-auto w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
